### ISSUE TITLE
BUG-000088157  Audio icons cut off when viewing story map application on a mobile device.

### ISSUE THREAD

**Issue by iwittenmyer** [Esri/side-accordion-map-storytelling-template-js#31]
<div><div>
<span><b>Salesforce ID:</b> BUG-000088157</span><br/>
<span><b>Salesforce Submitter:</b> Raynah Kamau</span><br/>
<span><b>Salesforce Submit Date:</b> 6/05/2015 3:21 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS Online</span><br/>
<span><b>Functional Category:</b> Story Map Templates</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 3.7</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by RupertEssinger** [comment]
Closing this:L the bug reported via Customer Care is for Story Map Tour and has been fixed. This Github repo is for the retired download only Side Accordion story map template.
